[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=/usr/sbin/php-fpm8.4 -F
autostart=true
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20

[program:laravel-queue]
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
directory=/var/www
user=www-data
autostart=true
autorestart=true
priority=30
stopwaitsecs=120
exitcodes=0
stdout_logfile=/var/log/queue.log
stderr_logfile=/var/log/queue-error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5